### ISSUE TITLE
`showHover` action doesn't work

### ISSUE THREAD

**Issue by JJ-Atkinson** [haystackeditor/haystack-editor#14]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90.0
- OS Version: Nixos (using linux appimage)
- Haystack Version: 0.18

Steps to Reproduce:

Normal behavior
1. Hover your mouse over a symbol
2. Wait for documention to popup
3. This action can be manually invoked with `editor.action.showHover` and bound to a shortcut

New behavior
1. Hover your mouse over a symbol
2. Popup shows as expected
3. Invoke the `showHover` keybinding, and nothing appears

**Comment by AkshaySG14** [comment]
Is this specifically in a symbol view i.e. when you don't view the whole file?

**Comment by JJ-Atkinson** [comment]
... apparently, yes! I didn't notice that until now.

**Comment by AkshaySG14** [comment]
This should be fixed in the latest version of Haystack on the website!
