### ISSUE TITLE
Save / Restore workspaces is very inconsistent. 

### ISSUE THREAD

**Issue by JJ-Atkinson** [haystackeditor/haystack-editor#16]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.90
- OS Version: Nixos (appimage)
- Haystack: 0.18, 0.19

Steps to Reproduce:

1. Save a workspace 
2. Close the editor
3. Reopen
4. Things are moved or missing

There's actually two different bugs here. It seems that if I save a workspace when at ... e.g. 80% zoom and try to restore it while at 120% zoom, things are moved around. That seems like a scaling bug. The other bug is more annoying, since I can remember to save/restore at 100% zoom. 

Before close
![image](https://github.com/user-attachments/assets/3a1a8d5b-6f71-4be5-ba65-edf18daf1733)
After re-open

![image](https://github.com/user-attachments/assets/709eb0cb-3abf-4cd8-bad9-832fbf10c40a)

(apologies, the viewports don't quite line up between the screenshot, but it should be pretty clear some of my editors got closed)

**Comment by AkshaySG14** [comment]
Sorry, the "other bug here" is that some editors got closed right? And does this happen only on Haystack close/reopen or also when you save/load canvas workspaces?

**Comment by JJ-Atkinson** [comment]
1. Scaling bug (not pictured) which is a bit more minor
2. Editor bug is when some of my tabs are closed. I can reproduce it by opening a different workspace and then opening the workspace I had saved. 

Thanks for taking a look!

**Comment by AkshaySG14** [comment]
This should be fixed in 0.19.1 on the website. Please let me know if something is still broken here!

**Comment by JJ-Atkinson** [comment]
It's still somewhat inconsistent, but much much better. I've noticed stacked editors sometimes, which I don't think is new but still happens in 0.19.1

**Comment by JJ-Atkinson** [comment]
Seems much better now btw
