### ISSUE TITLE
Make Haystack auto update

### ISSUE THREAD

**Issue by AkshaySG14** [haystackeditor/haystack-editor#20]
Make Haystack auto-update rather than requiring users to download the new binary.

**Comment by nang-dev** [comment]
This is how we did it. Works great.

vscode fork side: 

<img width="1545" alt="Screenshot 2024-10-07 at 1 45 09 PM" src="https://github.com/user-attachments/assets/5bf80ed5-cd27-4c70-b385-344413fc2e73">

<img width="1570" alt="Screenshot 2024-10-07 at 1 45 21 PM" src="https://github.com/user-attachments/assets/04342039-9f2c-4341-b068-9a033cb59594">

serverside: we return a link that is in DigitalOcean. We also tried with Google Drive and that also worked :)
<img width="730" alt="Screenshot 2024-10-07 at 1 47 05 PM" src="https://github.com/user-attachments/assets/edaa5216-ad17-426a-b4bd-d0875dc359bc">

Useful links:
https://www.electronjs.org/docs/latest/api/auto-updater
https://github.com/Squirrel/Squirrel.Mac#server-support

This should get autoupdating up and running! :) Good luck. Big supporter of Haystack
