### ISSUE TITLE
The image will remain fixed on the screen after renaming the image file while the file is open

### ISSUE THREAD

**Issue by srnabab** [haystackeditor/haystack-editor#26]
When clicking the image file multiple times, the file opens multiple times. Also, the rename shortcut (F2) doesn't work. After renaming the image file while it's open, only one window remains, and the image becomes fixed in a certain position.
<img width="1684" alt="image" src="https://github.com/user-attachments/assets/07caff03-6c43-46e6-bfba-3086e7d156c5">
<img width="935" alt="image" src="https://github.com/user-attachments/assets/b33e8ebb-ea11-4675-a43f-57de33f23911">

Does this issue occur when all extensions are disabled?: Yes

- Haystack Version: 0.19.1
- VS Code Version: 1.90.0 (user setup)
- OS Version: Windows 11 Pro 23H2

Steps to Reproduce:

1. left-click an image file multiple times
2. Right-click the image file and rename it

**Comment by AkshaySG14** [comment]
This should be fixed in the next release. Apologies for the issues here!

**Comment by AkshaySG14** [comment]
Sorry I never got back to this, but it should be fixed in 0.19.2 and 0.19.3!
