### ISSUE TITLE
Every time a workspace is opened, diff windows appear

### ISSUE THREAD

**Issue by JJ-Atkinson** [haystackeditor/haystack-editor#32]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 0.19.2
- OS Version:

Steps to Reproduce:

1. Open haystack
2. Check that you are on a clean git workspace
3. Re-open an old workspace
4. See two random diffs in your workspace that aren't even files you had in the workspace

![image](https://github.com/user-attachments/assets/31b4ce77-1c8c-4b51-b5f2-72eace3b7211)

**Comment by JJ-Atkinson** [comment]
for me this also seems to be the same two diff files every time, weirdly

**Comment by AkshaySG14** [comment]
I think this bug occurs because I messed up some logic regarding merge editors. This should be fixed in 0.19.3! Please let me know if it's still broken.

**Comment by JJ-Atkinson** [comment]
Perfect, I haven't hit it since upgrading to 0.19.4!
