### ISSUE TITLE
"Callers"/"Outgoing calls" arrows are not there ?

### ISSUE THREAD

**Issue by implicitdef** [haystackeditor/haystack-editor#40]
Haystack Version: 0.19.6
VS Code Version: 1.90.0
Chromium: 122.0.6261.156
OS: {3 }

macOs 14.4.1 (23E224) 

Tested on a Typescript/React codebase.

Hi
I've just download this to try it out. I looked at the demo video and the demo gif on the homepage. I understand that there's two arrows on the right of each editor that are supposed to show up ?

I don't have them and I can't seem to find a way to do the equivalent. I have played with all buttons and menus I could find and I have not been able to open new editors linked as a graph like in the demo.

I don't know if the demos are just outdated ? If so you may have a UX discovery problem... I've patiently tried using the editor for 10-15 minutes and still don't understand how to make use of it :/

<img width="1512" alt="Screenshot 2024-12-01 at 19 45 32" src="https://github.com/user-attachments/assets/35b3d0a0-ca0d-4735-bfc1-978ac778c395">

**Comment by AkshaySG14** [comment]
Hiya! The incoming/outgoing calls should work for functions and methods only. Is your selection inside a method or function?  Unfortunately it doesn't work for variables, even if they are essentially function objects.

**Comment by eletallbetagouv** [comment]
Ah ok, got it... I'm working on two big codebases at the moment, and they use the syntax `const something = () => .....` everywhere :/ 
It does work on smaller project that uses `function`.

**Comment by implicitdef** [comment]
Ah ok, got it... I'm working on two big codebases at the moment, and they use the syntax const something = () => ..... everywhere :/
It does work on a smaller project that uses function.
