### ISSUE TITLE
request body must contain the following parameter: 'client_assertion' or 'client_secret'

### ISSUE THREAD

**Issue by 3052** [haystackeditor/haystack-editor#41]
https://github.com/haystackeditor/haystack-editor/blob/3f235f43c423c1ea942668bdcf6713599b9a9936/cli/src/auth.rs#L711-L721

~~~
{"error":"invalid_client",
"error_description":"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'. Trace ID: 6ee9ec92-6726-422a-85ce-86a1a6502800 Correlation ID: 521b9148-40bc-455a-ace1-c13802e053eb Timestamp: 2024-12-03 13:51:30Z",
"error_codes":[7000218],
"timestamp":"2024-12-03 13:51:30Z",
"trace_id":"6ee9ec92-6726-422a-85ce-86a1a6502800",
"correlation_id":"521b9148-40bc-455a-ace1-c13802e053eb",
"error_uri":"https://login.microsoftonline.com/error?code=7000218"}
~~~

**Comment by AkshaySG14** [comment]
May I know what you're trying to accomplish here? We don't support CLI (it's not been a focus for us). Would be happy to help with more info!

**Comment by 3052** [comment]
I think I was using the wrong `client_id` - this works

https://github.com/haystackeditor/haystack-editor/blob/3f235f43c423c1ea942668bdcf6713599b9a9936/cli/src/auth.rs#L75-L80
