### ISSUE TITLE
chinese chat gpt can not work!!!

### ISSUE THREAD

**Issue by hello432369** [haystackeditor/haystack-editor#5]
vscode  and  cursor no problem
but haystack-editor can not work
there is something bug
I love haystack-editor 
please let this bug go to see God.

![longshot20240927141336](https://github.com/user-attachments/assets/f5fe3519-a3d4-4448-95d5-0be1969844c5)
![longshot20240927141210](https://github.com/user-attachments/assets/cd956015-8cc5-4c4f-bde7-bbad4696da85)
![longshot20240927141226](https://github.com/user-attachments/assets/483fbe15-e5a6-479a-a4a2-b6e238d330a7)

![longshot20240927143324](https://github.com/user-attachments/assets/cfc92b16-3484-4a4e-9620-ee71400c6229)

**Comment by AkshaySG14** [comment]
Ah unfortunately the chat window is broken in Haystack. Will fix.

**Comment by AkshaySG14** [comment]
This should be fixed in 0.19.3! Please let me know if it's still broken.

**Comment by hello432369** [comment]
it work !  nice
![longshot20241124013911](https://github.com/user-attachments/assets/5aa3c8f4-6541-4e08-ba8b-12bb802d8146)
