### ISSUE TITLE
Keyboard Shortcuts problem

### ISSUE THREAD

**Issue by Cthutu** [haystackeditor/haystack-editor#9]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version: Linux Pop_OS

Steps to Reproduce:

1. Open an editor window
2. Type "Ctrl+K, Ctrl+S" - notice how the shortcut doesn't work.
3. Click on the canvas deselecting the editor window
4. Type "Ctrl+K, Ctrl+S" - notice how the shortcut now works.

It seems that "Ctrl+S" has been overridden to save.  When unbinding Ctrl+S from saving, it still saves.  I use bind Ctrl+S to something else and only by selecting the canvas does it work.

**Comment by AkshaySG14** [comment]
This should be fixed with the latest version of Haystack (0.19) on the website!
